include:
  - 'templates/secret-find.yml'
  - 'templates/sast-scan.yml'
  - 'templates/sca-from-code.yml'
  - 'templates/sca-from-images.yml'
  - 'templates/dast-scan.yml'
  - 'templates/dockerfile-check.yml'
  - 'templates/build.yml'
  - 'templates/deploy.yml'

variables:
  HOST: <IP>
  PORT: <PORT>
  TARGET_URL: <URL>
  ZAP_AUTH_HEADER: Cookie
  ZAP_AUTH_HEADER_VALUE: Uid=1;Level=Low;govwa=<HEADER>
  GIT_STRATEGY: clone
  RUNNER_GENERATE_ARTIFACTS_METADATA: "true"
  SLSA_PROVENANCE_SCHEMA_VERSION: v1
  TOKEN: <YOUR TOKEN>

stages:
  - pre-build
  - build 
  - post-build
  - test-time
  - deploy