include:
  - 'templates/secret-find.yml'
  - 'templates/sast-scan.yml'
  - 'templates/sca-from-code.yml'
  - 'templates/sca-from-images.yml'
  - 'templates/dast-scan.yml'
  - 'templates/dockerfile-check.yml'

variables:
  HOST: 10.28.46.9
  PORT: 8888
  TARGET_URL: http://10.28.46.9:8888/index
  ZAP_AUTH_HEADER: Cookie
  ZAP_AUTH_HEADER_VALUE: Uid=1;Level=Low;govwa=MTcyMzgwNDQwM3xEWDhFQVFMX2dBQUJFQUVRQUFCZV80QUFBd1p6ZEhKcGJtY01Ed0FOWjI5MmQyRmZjMlZ6YzJsdmJnUmliMjlzQWdJQUFRWnpkSEpwYm1jTUJ3QUZkVzVoYldVR2MzUnlhVzVuREFjQUJXRmtiV2x1Qm5OMGNtbHVad3dFQUFKcFpBWnpkSEpwYm1jTUF3QUJNUT09fGXEMryLz7kW12-vZ5PSK0v_o3r9Nxc-4Ppvmgvfa4jZ
  GIT_STRATEGY: clone
  RUNNER_GENERATE_ARTIFACTS_METADATA: "true"
  SLSA_PROVENANCE_SCHEMA_VERSION: v1
  TOKEN: f204d7f7f60f03285f0b83b425fda504ec0bd87bfd707008ddc1218375ef0027


stages:
  - pre-build
  - build 
  - post-build
  - test-time
  - deploy

build:
  stage: build
  tags:
    - vm
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    BUILD_CONTEXT: "."
  script:
    - |-
      # 'Docker login'
      mkdir -p /kaniko/.docker
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |-
       /kaniko/executor --context "${CI_PROJECT_DIR}/${BUILD_CONTEXT}" \
                        --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
                        --cache=true \
                        --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}.${CI_PIPELINE_ID}"
  rules: 
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile 
  needs: 
    - semgrep-oss
    - scan-ptai
    - cdxgen
    - trivy-generate-bom-from-code
    - dependency_check
    - trivy-sca
    - gitleaks
    - trufflehog

deploy:
  stage: deploy
  script:
    - |-
      echo "Done deploy!"