hadolint:
  stage: pre-build
  image: 
    name: homebrew/brew
    entrypoint: [""] 
  allow_failure: true
  tags: 
    - vm 
  before_script:
    - brew install hadolint
  script:
    - hadolint $CI_PROJECT_DIR/govwa/Dockerfile -f json -c $CI_PROJECT_DIR/configure-files/hadolint/config.yml > $CI_PROJECT_DIR/hadolint-report.json
  artifacts:
    paths:
      - $CI_PROJECT_DIR/hadolint-report.json